//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karnel_Travel_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class bookingHot
    {
        public string bhot_id { get; set; }
        public string bhot_cust_id { get; set; }
        public string bhot_name { get; set; }
        public System.DateTime bhot_departure { get; set; }
        public System.DateTime bhot_arrival { get; set; }
        public int bhot_guests { get; set; }
        public int bhot_rooms { get; set; }
        public string bhot_contactNo { get; set; }
    
        public virtual hotel hotel { get; set; }
        public virtual userDetail userDetail { get; set; }
    }
}
