//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karnel_Travel_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class bookingReso
    {
        public string breso_id { get; set; }
        public string breso_cust_id { get; set; }
        public string breso_name { get; set; }
        public System.DateTime breso_departure { get; set; }
        public System.DateTime breso_arrival { get; set; }
        public int breso_guests { get; set; }
        public int breso_rooms { get; set; }
        public string breso_contactNo { get; set; }
    
        public virtual resort resort { get; set; }
        public virtual userDetail userDetail { get; set; }
    }
}
