//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karnel_Travel_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact
    {
        public string cont_id { get; set; }
        public string cont_email { get; set; }
        public string cont_formType { get; set; }
        public System.DateTime cont_dateTime { get; set; }
        public string cont_message { get; set; }
        public string cont_name { get; set; }
    }
}
