//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karnel_Travel_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public string cust_id { get; set; }
        public string cust_name { get; set; }
        public string cust_contactNo { get; set; }
        public string cust_email { get; set; }
        public string cust_nic { get; set; }
        public string cust_u_id { get; set; }
        public string cust_u_password { get; set; }
    }
}
