//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karnel_Travel_Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class karnelEntities1 : DbContext
    {
        public karnelEntities1()
            : base("name=karnelEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adminDetail> adminDetail { get; set; }
        public virtual DbSet<bookingHot> bookingHot { get; set; }
        public virtual DbSet<bookingReso> bookingReso { get; set; }
        public virtual DbSet<bookingTran> bookingTran { get; set; }
        public virtual DbSet<contact> contact { get; set; }
        public virtual DbSet<customer> customer { get; set; }
        public virtual DbSet<hotel> hotel { get; set; }
        public virtual DbSet<resort> resort { get; set; }
        public virtual DbSet<restaurant> restaurant { get; set; }
        public virtual DbSet<tranport> tranport { get; set; }
        public virtual DbSet<userDetail> userDetail { get; set; }
    }
}
