//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karnel_Travel_Project
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class resort
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public resort()
        {
            this.bookingReso = new HashSet<bookingReso>();
        }
    
        public string reso_id { get; set; }
        public string reso_name { get; set; }
        public string reso_country { get; set; }
        public decimal reso_charges { get; set; }
        public int reso_roomAvailable { get; set; }
        public Nullable<int> reso_rating { get; set; }
        public string reso_description { get; set; }
        public string reso_img { get; set; }
        public HttpPostedFileBase imageFile { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bookingReso> bookingReso { get; set; }
    }
}
