//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karnel_Travel_Project
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class restaurant
    {
        public string rest_id { get; set; }
        public string rest_name { get; set; }
        public string rest_country { get; set; }
        public decimal rest_charges { get; set; }
        public Nullable<int> rest_rating { get; set; }
        public string rest_description { get; set; }
        public string rest_img { get; set; }
        public HttpPostedFileBase imageFile { get; set; }
    }
}
