//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karnel_Travel_Project
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class tranport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tranport()
        {
            this.bookingTran = new HashSet<bookingTran>();
        }
    
        public string tran_id { get; set; }
        public string tran_name { get; set; }
        public string tran_country { get; set; }
        public decimal tran_charges { get; set; }
        public int tran_seatAvailable { get; set; }
        public string tran_description { get; set; }
        public string tran_img { get; set; }
        public HttpPostedFileBase imageFile { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bookingTran> bookingTran { get; set; }
    }
}
